### ISSUE TITLE
Success Message Displayed even when error occurs

### ISSUE THREAD

**Issue by kevgathuku** [kn9ts/frodo#1]
When an error occurs when trying to launch the application, both the error and the success message are displayed.
Example: Using an invalid port number e.g. `App.ServeOnPort("invalid")` produces the following message

``` bash
[Frodo] 2015/09/18 09:57:40 Error: server failed to initialise: listen tcp: lookup tcp/invalid: Servname not supported for ai_socktype
[Frodo] 2015/09/18 09:57:40 Server deployed at: invalid
```

**Comment by kevgathuku** [comment]
On a related note, I just realized that the success message is never displayed even when the app starts successfully.
Once the server starts, the [`Log.Success`](https://github.com/kn9ts/frodo/blob/master/router.go#L627) function is never reached. 
@kn9ts any thoughts on this?

**Comment by kn9ts** [comment]
@kevgathuku Was this solved? I can not recall solving it.
