### ISSUE TITLE
Why there is no tests?

### ISSUE THREAD

**Issue by gernest** [kn9ts/frodo#10]
Any reason why there  is no tests in frodo?

**Comment by kn9ts** [comment]
:octocat: I was testing the framework live (live testing), no TDD driven development. It was DDD (developer driven development)

**Comment by gernest** [comment]
@kn9ts use of past tense, does this imply you no longer do that?

Off topic. I just realized you closed my issues after just one reply?

**Comment by kn9ts** [comment]
I do it when only relevant. This was a project for to learn Go, and ofcos the internals of most frameworks. This though doesnt mean that it can not be used in a prod environment. I did test it heavily too but using DDD.

**Comment by gernest** [comment]
👍
