### ISSUE TITLE
Misleading information on README

### ISSUE THREAD

**Issue by gernest** [kn9ts/frodo#8]
On the README  [here](https://github.com/kn9ts/frodo#updates) it is metioned that frodo is using httprouter internally which as for the current master branch is not true.

Maybe I missed something? I have gone thought all the package imports and couldn't find http router!

[ Shameless plug] I can help you migrate to [alien](https://github.com/gernest/alien) you can use it internally as your router, it is lightweight and in a few lines of Go 456 slock together with comments!

**Comment by kn9ts** [comment]
I did not import and use it as a library thus wrap my routes business logic around it. I took httprouter's radix trie algorithm routing and interweaved my code with it.
