### ISSUE TITLE
Which tree data structure is used by frodo?

### ISSUE THREAD

**Issue by gernest** [kn9ts/frodo#9]
There is a tree implementation  here https://github.com/kn9ts/frodo/blob/master/tree.go but going around I couldn't grok what tree is used.

I find tries to be more performant when it comes to string matching. And the lack of tests makes  it harder to verify if the implementation is correct.

In case you want to move to a different router this won't be the case.

**Comment by kn9ts** [comment]
It's using http-router's radix trie algorithm. That is not actually my code but the http-router's code borrowed and interweaved into the frodo framework code
